
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author uchag
 */
public class Flights extends javax.swing.JFrame {

    /**
     * Creates new form Flights
     */
    public Flights() {
        initComponents();
        DisplayFlights();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        FCode = new javax.swing.JTextField();
        SeatsTb = new javax.swing.JTextField();
        FSourceCB = new javax.swing.JComboBox<>();
        FDestCB = new javax.swing.JComboBox<>();
        SaveBtn = new javax.swing.JButton();
        EdtBtn = new javax.swing.JButton();
        DelBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlightsTable = new javax.swing.JTable();
        FDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(186, 228, 229));

        jLabel7.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 102));
        jLabel7.setText("DJB Airlines");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(659, 659, 659)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 102));
        jLabel1.setText("FLIGHT CODE");

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setText("SOURCE");

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setText("DESTINATION");

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 102));
        jLabel4.setText("TAKE OFF DATE");

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 102));
        jLabel5.setText("NUMBER OF SEATS");

        FCode.setBackground(new java.awt.Color(0, 102, 0));
        FCode.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        FCode.setForeground(new java.awt.Color(102, 204, 0));
        FCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FCodeActionPerformed(evt);
            }
        });

        SeatsTb.setBackground(new java.awt.Color(0, 102, 0));
        SeatsTb.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        SeatsTb.setForeground(new java.awt.Color(102, 204, 0));
        SeatsTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatsTbActionPerformed(evt);
            }
        });

        FSourceCB.setBackground(new java.awt.Color(0, 102, 0));
        FSourceCB.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        FSourceCB.setForeground(new java.awt.Color(102, 204, 0));
        FSourceCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MUMBAI\t\t\t\t", "DELHI", "CHENNAI", "BANGLORE", "KOLKATA", "HYDERABAD", "AHMEDABAD", "SURAT", "PUNE", "JAIPUR", "LUCKNOW", " " }));

        FDestCB.setBackground(new java.awt.Color(0, 102, 0));
        FDestCB.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        FDestCB.setForeground(new java.awt.Color(102, 204, 0));
        FDestCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MUMBAI\t\t\t\t", "DELHI", "CHENNAI", "BANGLORE", "KOLKATA", "HYDERABAD", "AHMEDABAD", "SURAT", "PUNE", "JAIPUR", "LUCKNOW", " " }));

        SaveBtn.setBackground(new java.awt.Color(0, 102, 102));
        SaveBtn.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        SaveBtn.setForeground(new java.awt.Color(0, 204, 153));
        SaveBtn.setText("SAVE");
        SaveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBtnMouseClicked(evt);
            }
        });
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });

        EdtBtn.setBackground(new java.awt.Color(0, 102, 102));
        EdtBtn.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        EdtBtn.setForeground(new java.awt.Color(0, 204, 153));
        EdtBtn.setText("EDIT");
        EdtBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdtBtnMouseClicked(evt);
            }
        });
        EdtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtBtnActionPerformed(evt);
            }
        });

        DelBtn.setBackground(new java.awt.Color(0, 102, 102));
        DelBtn.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        DelBtn.setForeground(new java.awt.Color(0, 204, 153));
        DelBtn.setText("DELETE");
        DelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DelBtnMouseClicked(evt);
            }
        });
        DelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelBtnActionPerformed(evt);
            }
        });

        BackBtn.setBackground(new java.awt.Color(0, 102, 102));
        BackBtn.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(0, 204, 153));
        BackBtn.setText("BACK");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 153, 102));
        jLabel6.setText("FLIGHT LIST");

        FlightsTable.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        FlightsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        FlightsTable.setName(""); // NOI18N
        FlightsTable.setRowHeight(35);
        FlightsTable.setShowGrid(true);
        FlightsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlightsTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(FlightsTable);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1)
                        .addGap(141, 141, 141)
                        .addComponent(jLabel2)
                        .addGap(148, 148, 148)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(FCode, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(FSourceCB, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FDestCB, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(122, 122, 122)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(FDate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(SeatsTb, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(172, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(SaveBtn)
                                .addGap(139, 139, 139)
                                .addComponent(EdtBtn)
                                .addGap(127, 127, 127)
                                .addComponent(DelBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(410, 410, 410)
                                .addComponent(jLabel6)))
                        .addGap(116, 116, 116)
                        .addComponent(BackBtn)
                        .addGap(533, 533, 533))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(196, 196, 196))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29))
                    .addComponent(jLabel5))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FCode, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(FSourceCB)
                        .addComponent(FDestCB))
                    .addComponent(FDate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeatsTb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DelBtn)
                    .addComponent(BackBtn)
                    .addComponent(EdtBtn)
                    .addComponent(SaveBtn))
                .addGap(54, 54, 54)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(240, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void DelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DelBtnActionPerformed

    private void EdtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdtBtnActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void SeatsTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatsTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatsTbActionPerformed

    private void FCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FCodeActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
       new Welcome().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked
   
    Connection Con = null;
    PreparedStatement pst = null;
 ResultSet Rs = null,Rs1 = null;
 Statement St =  null,St1 = null;
 private void DisplayFlights(){
     {
         try{
             Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","Daniel@#1234");
             St = Con.createStatement();
             Rs = St.executeQuery("select *from flighttable");
             FlightsTable.setModel(DbUtils.resultSetToTableModel(Rs));
         }catch(Exception e){
     }
 }}
   private void Clear(){
        FCode.setText("");
        SeatsTb.setText("");
     
    }
    private void SaveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBtnMouseClicked
      
          if(FCode.getText().isEmpty() || SeatsTb.getText().isEmpty() || FSourceCB.getSelectedIndex()==-1 ||  FDestCB.getSelectedIndex()==-1 )
         {
           JOptionPane.showMessageDialog(this,"Missing Information");
         }else{
             try{
                    
                    
             
                  Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","Daniel@#1234");
                  PreparedStatement Add  =  Con.prepareStatement("insert into flighttable values(?,?,?,?,?)");
                  Add.setString(1, FCode.getText());
                  
                  Add.setString(2, FSourceCB.getSelectedItem().toString());
                  Add.setString(3, FDestCB.getSelectedItem().toString());
                  Add.setString(4, FDate.getDate().toString());
                  Add.setInt(5, Integer.valueOf(SeatsTb.getText()));
                  
                  
                  int row = Add.executeUpdate();
                  JOptionPane.showMessageDialog(this,"Flight Added");
                  Con.close();
                  DisplayFlights();
                  Clear();
             }catch(Exception e){
                 JOptionPane.showMessageDialog(this, e);
                 
             }
         }
    }//GEN-LAST:event_SaveBtnMouseClicked
String Key = "";
    private void DelBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelBtnMouseClicked
         if(Key == ""){
          JOptionPane.showMessageDialog(this, "select a Flight");
      }else{
          try{
               Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","Daniel@#1234");
               String Query = "Delete from flighttable where FlightCode ='"+Key+"'";
               Statement Del = Con.createStatement();
               Del.executeUpdate(Query);
               JOptionPane.showMessageDialog(this,"Flight Deleted");
               DisplayFlights();
          }catch(Exception e){
              JOptionPane.showMessageDialog(this, e);
              
          
      }
    }    
    }//GEN-LAST:event_DelBtnMouseClicked

    private void FlightsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlightsTableMouseClicked
        
                                                   
        DefaultTableModel model = (DefaultTableModel)FlightsTable.getModel();
        int MyIndex = FlightsTable.getSelectedRow();
        Key = model.getValueAt(MyIndex, 0).toString();
      
        FSourceCB.setSelectedItem(model.getValueAt(MyIndex, 2).toString());
         FDestCB.setSelectedItem(model.getValueAt(MyIndex, 3).toString());
        SeatsTb.setText(model.getValueAt(MyIndex, 5).toString());
       
         
     
    }//GEN-LAST:event_FlightsTableMouseClicked

    private void EdtBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdtBtnMouseClicked
   if(Key == "")
         {
           JOptionPane.showMessageDialog(this,"Select A Passenger");
         }else{
             try{
                   
                    
             
                  Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","Daniel@#1234");
                  String Query = "Update flighttable set FlightSource=?,FlightDestination=?,FlightDtae=?,Seats=? where FlightCode = ?";
                  
                  PreparedStatement Add  =  Con.prepareStatement(Query);
                  Add.setString(5,Key );
                
                  Add.setString(1, FSourceCB.getSelectedItem().toString());
                  Add.setString(2, FDestCB.getSelectedItem().toString());
                  Add.setString(3,FDate.getDate().toString());
                  Add.setString(4,SeatsTb.getText());
                
            
                  
                  int row = Add.executeUpdate();
                  JOptionPane.showMessageDialog(this,"Passenger Updated");
                  Con.close();
                  DisplayFlights();
                  Clear();
             }catch(Exception e){
                 JOptionPane.showMessageDialog(this, e);
                 
             }
         }
    }//GEN-LAST:event_EdtBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flights.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flights().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton DelBtn;
    private javax.swing.JButton EdtBtn;
    private javax.swing.JTextField FCode;
    private com.toedter.calendar.JDateChooser FDate;
    private javax.swing.JComboBox<String> FDestCB;
    private javax.swing.JComboBox<String> FSourceCB;
    private javax.swing.JTable FlightsTable;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField SeatsTb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
