
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author uchag
 */
public class Passengers extends javax.swing.JFrame {

    private boolean PaddressTb;
    private Object PNameTb;

    /**
     * Creates new form PAssengers
     */
    public Passengers() {
        initComponents();
     DisplayPassengers();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Passenger_Name = new javax.swing.JTextField();
        PAddressTb = new javax.swing.JTextField();
        NatCb = new javax.swing.JComboBox<>();
        GenCb = new javax.swing.JComboBox<>();
        Savebtn = new javax.swing.JButton();
        Edtbtn = new javax.swing.JButton();
        Delbtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        PassengersTable = new javax.swing.JTable();
        PassNumTb = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        PPhoneTb = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        jLabel13.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 102));
        jLabel13.setText("PASSENGER NAME");

        jLabel14.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 102));
        jLabel14.setText("NATIONALITY");

        jLabel15.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 102));
        jLabel15.setText("GENDER");

        jLabel16.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 102));
        jLabel16.setText("PASSPORT NUMBER");

        jLabel17.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 102));
        jLabel17.setText("ADDRESS");

        Passenger_Name.setBackground(new java.awt.Color(0, 102, 0));
        Passenger_Name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Passenger_Name.setForeground(new java.awt.Color(102, 204, 0));
        Passenger_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Passenger_NameActionPerformed(evt);
            }
        });

        PAddressTb.setBackground(new java.awt.Color(0, 102, 0));
        PAddressTb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PAddressTb.setForeground(new java.awt.Color(102, 204, 0));
        PAddressTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAddressTbActionPerformed(evt);
            }
        });

        NatCb.setBackground(new java.awt.Color(0, 102, 0));
        NatCb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        NatCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INDIA", "USA", "ENGLAND", "CHINA", "JAPAN", "SPAIN", "FRANCE", "AFRICA", "UAE", "AMSTRADAM", "RUSSIA", "PAKISTAN", "ITALY", "UKRANE", "ICELAND", "SINGAPORE", "MYANMAR", "GERMANY", " ", " ", " ", " " }));

        GenCb.setBackground(new java.awt.Color(0, 102, 0));
        GenCb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        GenCb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE", "OTHER", " " }));

        Savebtn.setBackground(new java.awt.Color(0, 102, 102));
        Savebtn.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Savebtn.setForeground(new java.awt.Color(0, 204, 153));
        Savebtn.setText("SAVE");
        Savebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SavebtnMouseClicked(evt);
            }
        });
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });

        Edtbtn.setBackground(new java.awt.Color(0, 102, 102));
        Edtbtn.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Edtbtn.setForeground(new java.awt.Color(0, 204, 153));
        Edtbtn.setText("EDIT");
        Edtbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EdtbtnMouseClicked(evt);
            }
        });
        Edtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdtbtnActionPerformed(evt);
            }
        });

        Delbtn.setBackground(new java.awt.Color(0, 102, 102));
        Delbtn.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        Delbtn.setForeground(new java.awt.Color(0, 204, 153));
        Delbtn.setText("DELETE");
        Delbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DelbtnMouseClicked(evt);
            }
        });
        Delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelbtnActionPerformed(evt);
            }
        });

        BackBtn.setBackground(new java.awt.Color(0, 102, 102));
        BackBtn.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        BackBtn.setForeground(new java.awt.Color(0, 204, 153));
        BackBtn.setText("BACK");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 102));
        jLabel18.setText("PASSENGERS LIST");

        PassengersTable.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        PassengersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        PassengersTable.setRowHeight(35);
        PassengersTable.setShowGrid(true);
        PassengersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassengersTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(PassengersTable);

        PassNumTb.setBackground(new java.awt.Color(0, 102, 0));
        PassNumTb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PassNumTb.setForeground(new java.awt.Color(102, 204, 0));
        PassNumTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassNumTbActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 102));
        jLabel19.setText("PHONE");

        PPhoneTb.setBackground(new java.awt.Color(0, 102, 0));
        PPhoneTb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        PPhoneTb.setForeground(new java.awt.Color(102, 204, 0));
        PPhoneTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PPhoneTbActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 102));
        jLabel20.setText("MANAGE PASSENGERS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(NatCb, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BackBtn)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15)
                                            .addComponent(GenCb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PassNumTb, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel16)))
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addComponent(PAddressTb, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(76, 76, 76)
                                                .addComponent(jLabel17)))))
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addComponent(PPhoneTb, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19)
                                        .addGap(68, 68, 68))))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(Passenger_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(359, 359, 359))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(Savebtn)
                                .addGap(118, 118, 118)))
                        .addComponent(Edtbtn)
                        .addGap(114, 114, 114)
                        .addComponent(Delbtn))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(565, 565, 565)
                        .addComponent(jLabel20)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel19)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Passenger_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                            .addComponent(NatCb)
                            .addComponent(GenCb)
                            .addComponent(PassNumTb)
                            .addComponent(PAddressTb)
                            .addComponent(PPhoneTb)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(82, 82, 82)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Savebtn)
                    .addComponent(Edtbtn)
                    .addComponent(Delbtn)
                    .addComponent(BackBtn))
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 Connection Con = null;
    PreparedStatement pst = null;
 ResultSet Rs = null,Rs1 = null;
 Statement St =  null,St1 = null;
 private void DisplayPassengers(){
     {
         try{
             Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","Daniel@#1234");
             St = Con.createStatement();
             Rs = St.executeQuery("select *from passengers_table");
             PassengersTable.setModel(DbUtils.resultSetToTableModel(Rs));
         }catch(Exception e){
     }
 }}
    private void Passenger_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Passenger_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Passenger_NameActionPerformed

    private void PAddressTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAddressTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PAddressTbActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavebtnActionPerformed

    private void EdtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdtbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdtbtnActionPerformed

    private void DelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DelbtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    private void PassNumTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassNumTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassNumTbActionPerformed

    private void PPhoneTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PPhoneTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PPhoneTbActionPerformed
    int PassId = 0;
    
    
    private void CountPassengers(){
        try{
            St1 = Con.createStatement();
            Rs1 = St1.executeQuery("select Max(PID) from passengers_table");
            Rs1.next();
            PassId = Rs1.getInt(1)+1;
            
            
            
        }catch(Exception e){
        
    }}
    private void Clear(){
        Passenger_Name.setText("");
        PassNumTb.setText("");
        PAddressTb.setText("");
        PPhoneTb.setText("");
    }
    
    private void SavebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SavebtnMouseClicked
         if(Passenger_Name.getText().isEmpty() || PassNumTb.getText().isEmpty() || PAddressTb.getText().isEmpty() || PPhoneTb.getText().isEmpty())
         {
           JOptionPane.showMessageDialog(this,"Missing Information");
         }else{
             try{
                     CountPassengers();
                    
             
                  Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","Daniel@#1234");
                  PreparedStatement Add  =  Con.prepareStatement("insert into passengers_table values(?,?,?,?,?,?,?)");
                  Add.setInt(1, PassId);
                  Add.setString(2, Passenger_Name.getText());
                  Add.setString(3, NatCb.getSelectedItem().toString());
                  Add.setString(4, GenCb.getSelectedItem().toString());
                  Add.setString(5, PassNumTb.getText());
                   Add.setString(6,PAddressTb.getText());
                  Add.setString(7,PPhoneTb.getText());
                  int row = Add.executeUpdate();
                  JOptionPane.showMessageDialog(this,"Passenger Added");
                  Con.close();
                  DisplayPassengers();
                  Clear();
             }catch(Exception e){
                 JOptionPane.showMessageDialog(this, e);
                 
             }
         }
    }//GEN-LAST:event_SavebtnMouseClicked

    private void DelbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelbtnMouseClicked
      if(Key == 0){
          JOptionPane.showMessageDialog(this, "select a Passenger");
      }else{
          try{
               Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","Daniel@#1234");
               String Query = "Delete from passengers_table where PId ="+Key;
               Statement Del = Con.createStatement();
               Del.executeUpdate(Query);
               JOptionPane.showMessageDialog(this,"Passenger Deleted");
               DisplayPassengers();
          }catch(Exception e){
              JOptionPane.showMessageDialog(this, e);
              
          }
      }
    }//GEN-LAST:event_DelbtnMouseClicked
     int Key = 0;
    private void PassengersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassengersTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)PassengersTable.getModel();
        int MyIndex = PassengersTable.getSelectedRow();
        Key = Integer.valueOf(model.getValueAt(MyIndex, 0).toString());
        Passenger_Name.setText(model.getValueAt(MyIndex, 1).toString());
        NatCb.setSelectedItem(model.getValueAt(MyIndex, 2).toString());
         GenCb.setSelectedItem(model.getValueAt(MyIndex, 3).toString());
         PAddressTb.setText(model.getValueAt(MyIndex, 5).toString());
        PassNumTb.setText(model.getValueAt(MyIndex, 4).toString());
        PPhoneTb.setText(model.getValueAt(MyIndex, 6).toString());
        
    }//GEN-LAST:event_PassengersTableMouseClicked

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        new Welcome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackBtnMouseClicked

    private void EdtbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdtbtnMouseClicked
         if(Key == 0)
         {
           JOptionPane.showMessageDialog(this,"Select A Passenger");
         }else{
             try{
                   
                    
             
                  Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/miniproject","root","Daniel@#1234");
                  String Query = "Update passengers_table set Passenger_Name=?,Passenger_Nat=?,Passenger_Gender=?,Passenger_pass=?,Passenger_Address=?,Passenger_PhoneNo=? where PID = ?";
                  
                  PreparedStatement Add  =  Con.prepareStatement(Query);
                  Add.setInt(7, Key);
                  Add.setString(1, Passenger_Name.getText());
                  Add.setString(2, NatCb.getSelectedItem().toString());
                  Add.setString(3, GenCb.getSelectedItem().toString());
                  Add.setString(4, PassNumTb.getText());
                   Add.setString(5,PAddressTb.getText());
                  Add.setString(6,PPhoneTb.getText());
                  int row = Add.executeUpdate();
                  JOptionPane.showMessageDialog(this,"Passenger Updated");
                  Con.close();
                  DisplayPassengers();
                  Clear();
             }catch(Exception e){
                 JOptionPane.showMessageDialog(this, e);
                 
             }
         }
    }//GEN-LAST:event_EdtbtnMouseClicked

    public static void main(String[] args){
   /* public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Passengers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Passengers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JButton Delbtn;
    private javax.swing.JButton Edtbtn;
    private javax.swing.JComboBox<String> GenCb;
    private javax.swing.JComboBox<String> NatCb;
    private javax.swing.JTextField PAddressTb;
    private javax.swing.JTextField PPhoneTb;
    private javax.swing.JTextField PassNumTb;
    private javax.swing.JTextField Passenger_Name;
    private javax.swing.JTable PassengersTable;
    private javax.swing.JButton Savebtn;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

   
}
